# Generated by Django 5.1.6 on 2025-03-14 17:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Painting',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255)),
                ('imageURL', models.URLField()),
                ('description', models.TextField(blank=True)),
            ],
        ),
    ]
