# Generated by Django 5.1.6 on 2025-04-26 11:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='painting',
            name='image',
        ),
        migrations.AddField(
            model_name='painting',
            name='imageURL',
            field=models.URLField(default='https://eurobyte.ru/img/articles/chto-takoe-url-adres/image2.png'),
            preserve_default=False,
        ),
    ]
