# Generated by Django 5.1.6 on 2025-03-14 18:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0004_alter_painting_tags'),
    ]

    operations = [
        migrations.AlterField(
            model_name='painting',
            name='tags',
            field=models.ManyToManyField(blank=True, null=True, related_name='tags', to='gallery.tag'),
        ),
    ]
