# Generated by Django 5.1.6 on 2025-03-15 11:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0006_alter_painting_tags'),
    ]

    operations = [
        migrations.CreateModel(
            name='Artist',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('biography', models.TextField()),
                ('photoURL', models.URLField()),
            ],
        ),
    ]
