# Generated by Django 5.1.6 on 2025-03-15 11:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0007_artist'),
    ]

    operations = [
        migrations.AddField(
            model_name='painting',
            name='artist',
            field=models.ManyToManyField(related_name='artists', to='gallery.artist'),
        ),
    ]
